---
title: "Forensic DNA analysis"
output: html_document
date: "2024-04-28"
site: workflowr::wflow_site
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/home/hannah/Lasisi_lab")
```

```{r data, results = FALSE,warning=FALSE,message=FALSE}
# load necessary libraries
library(readr)
library(tidycensus)
library(tidyverse)
library(ggplot2)
library(viridis)

# load prison data
prison_data = read.csv("./data/populations_states.csv")

# load CODIS data
codis_data = read.csv("./data/CODIS_data.csv")

# only get data from 2022
prison_data$year = substring(prison_data$date,1,4)
prison_data_2022 = prison_data[which(prison_data$year == "2022"),]
prison_data_2022 = prison_data_2022[!duplicated(prison_data_2022[,c('state')]),]
```
### Loading census data for each state:
### P003001 is the total population and P003003 is the total Black population
```{r census, results = FALSE,warning=FALSE,message=FALSE}
vars <- c("P003001","P003003")

us_state_density <- get_decennial(
  geography = "state",
  variables = c(all = "P1_002N",black = "P1_004N"),
  year = 2020,
  geometry = TRUE,
  keep_geo_vars = TRUE
) 
us_state_density = spread(us_state_density, variable, value)
us_state_density$pb = us_state_density$black / us_state_density$all

us_state_density$state = us_state_density$NAME.x
us_state_density = merge(us_state_density, prison_data_2022, by = "state")
us_state_density$pb_carc = us_state_density$incarcerated_black / us_state_density$incarcerated_total

us_state_density = merge(us_state_density, codis_data, by = "state")
us_state_density$black_profiles = us_state_density$pb_carc * us_state_density$arrestee_profiles

us_state_density = us_state_density %>%
  tigris::shift_geometry()

```
### Percent of prison population that is Black
```{r,warning=FALSE,out.width="100%"}
ggplot() +
  geom_sf(data = us_state_density, aes(fill = us_state_density$pb_carc),color = NA) + 
  theme_void(base_size = 11) + 
  scale_fill_viridis(option = "magma", direction = -1)+
  labs(fill = "") + 
  geom_sf(data = us_state_density$geometry, color = "black",lwd = 0.1,alpha = 0) 
```

### Difference between percent of prison population that is Black and percent of general population that is Black
```{r,warning=FALSE,out.width="100%"}
ggplot() +
  geom_sf(data = us_state_density, aes(fill = us_state_density$pb_carc - us_state_density$pb),color = NA) + 
  theme_void(base_size = 11) + 
  scale_fill_viridis(option = "magma", direction = -1)+
  labs(fill = "") + 
  geom_sf(data = us_state_density$geometry, color = "black",lwd = 0.1,alpha = 0) 
```








